trigger:
  branches:
    include:
      - main

variables:
  imageName: 'ghcr.io/fhcloutier/mssql'
  tag: '2019-latest'

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build Image
    pool:
      name: Default
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - script: |
        echo "Logging into GHCR"
        echo $(GHCR_PAT) | docker login ghcr.io -u $(GHCR_USERNAME) --password-stdin
      displayName: Docker Login

    - script: |
        docker build -t $(imageName):$(tag) -f "Question 3/Dockerfile" "Question 3"
      displayName: Build Image

    - script: |
        docker push $(imageName):$(tag)
      displayName: Push Image